name: Integration Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  integration-tests:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'
        cache: 'npm'
    
    - name: Install Node.js dependencies
      run: npm ci
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        cache: 'pip'
    
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .
        pip install -r requirements-dev.txt
        pip install pytest reportlab web3 eth_account
    
    - name: Start Hardhat node
      run: |
        npx hardhat node &
        echo "HARDHAT_NODE_PID=$!" >> $GITHUB_ENV
        sleep 5  # Give the node time to start
    
    - name: Deploy contract to local node
      run: npx hardhat run scripts/deploy.js --network localhost
    
    - name: Run integration tests
      run: |
        pytest -xvs tests/integration_tests/ --cleanup
    
    - name: Stop Hardhat node
      if: always()
      run: |
        if [ -n "$HARDHAT_NODE_PID" ]; then
          kill $HARDHAT_NODE_PID || true
        fi
