name: Integration Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  integration-tests:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'
        cache: 'npm'
    
    - name: Install Node.js dependencies
      run: npm ci
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        cache: 'pip'
    
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        python -m venv test_venv
        source test_venv/bin/activate
        pip install -e .
        pip install -r requirements-dev.txt
    
    - name: Setup for integration tests
      run: |
        chmod +x tests/integration_tests/setup.sh
        chmod +x tests/integration_tests/teardown.sh
        ./tests/integration_tests/setup.sh
    
    - name: Run integration tests
      run: |
        source test_venv/bin/activate
        pytest -xvs tests/integration_tests/ --cleanup
    
    - name: Teardown after integration tests
      if: always()
      run: |
        ./tests/integration_tests/teardown.sh
